python baseline.py --seed 0
python baseline.py --seed 1
python baseline.py --seed 2
python baseline.py --seed 42
python baseline.py --seed 2023
python baseline.py --seed 3407
python baseline.py --seed 10
python baseline.py --seed 100
python baseline.py --seed 1000
python baseline.py --seed 10000
python baseline.py --seed 3
python baseline.py --seed 5
python baseline.py --seed 7
python baseline.py --seed 11
python baseline.py --seed 13
python baseline.py --seed 17
python baseline.py --seed 23
python baseline.py --seed 31
python baseline.py --seed 37
python baseline.py --seed 41
python baseline.py --seed 43
python baseline.py --seed 47
python baseline.py --seed 53
python baseline.py --seed 59
python baseline.py --seed 61
python baseline.py --seed 67
python baseline.py --seed 71
python baseline.py --seed 73
python baseline.py --seed 79
python baseline.py --seed 83
python baseline.py --seed 89
python baseline.py --seed 97
